table f_despesas_casal
	lineageTag: f7b402b5-44f9-4a48-8823-0bcbab6d7053

	column Conta
		dataType: string
		lineageTag: e95d9ff9-820b-47b5-b25d-53b54b49c762
		summarizeBy: none
		sourceColumn: Conta

		annotation SummarizationSetBy = Automatic

	column 'Título da transação'
		dataType: string
		lineageTag: 959a8128-14ab-4650-897c-55097a0190dc
		summarizeBy: none
		sourceColumn: Título da transação

		annotation SummarizationSetBy = Automatic

	column Banco
		dataType: string
		lineageTag: 6f3ba1f8-547d-4821-8a5a-f75a3be6431c
		summarizeBy: none
		sourceColumn: Banco

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 6189a199-69ce-4d52-851c-b48851d3e178
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: ad861855-dbcb-4d4e-81e8-dfb7efe0c660
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Categoria Despesa'
		dataType: string
		lineageTag: 9209d7f3-0823-4999-b121-f2c610c5235d
		summarizeBy: none
		sourceColumn: Categoria Despesa

		annotation SummarizationSetBy = Automatic

	column Modalidade
		dataType: string
		lineageTag: 1082924a-a401-4281-8b72-7856618d5730
		summarizeBy: none
		sourceColumn: Modalidade

		annotation SummarizationSetBy = Automatic

	column 'Fonte dinheiro'
		dataType: string
		lineageTag: 6ddea05a-5698-4fc2-b2d7-31dc914bcfa1
		summarizeBy: none
		sourceColumn: Fonte dinheiro

		annotation SummarizationSetBy = Automatic

	column tabela
		dataType: string
		lineageTag: 8a807333-de6c-4691-9628-985d09790cc9
		summarizeBy: none
		sourceColumn: tabela

		annotation SummarizationSetBy = Automatic

	column 'Qtidade de parcelas'
		dataType: string
		lineageTag: 408f5bf0-9be6-47e1-bcdf-7ea87905d541
		summarizeBy: none
		sourceColumn: Qtidade de parcelas

		annotation SummarizationSetBy = Automatic

	column 'Tirar linha do dashboard'
		dataType: string
		lineageTag: 0cc6202d-d483-49b1-ab3e-97e2dcada2bb
		summarizeBy: none
		sourceColumn: Tirar linha do dashboard

		annotation SummarizationSetBy = Automatic

	partition f_despesas_casal = m
		mode: import
		queryGroup: GOLD
		source =
				let
				    Fonte = #"Base de dados",
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Carimbo de data/hora"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Tipo] = "Despesa")),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Linhas Filtradas",{"Categoria Receitas", "Tipo"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"Valor", Currency.Type}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each ([Conta] = "Casal")),
				    #"Personalização Adicionada" = Table.AddColumn(#"Linhas Filtradas1", "tabela", each 1)
				in
				    #"Personalização Adicionada"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

