table f_despesas
	lineageTag: 290cf276-2ced-4a13-9cf2-d85b7793899c

	column Conta
		dataType: string
		lineageTag: b47600bd-cd96-4bc2-b202-625980cb076c
		summarizeBy: none
		sourceColumn: Conta

		annotation SummarizationSetBy = Automatic

	column 'Título da transação'
		dataType: string
		lineageTag: c03d6bdf-6e30-411a-bb5f-75a661c6ffe8
		summarizeBy: none
		sourceColumn: Título da transação

		annotation SummarizationSetBy = Automatic

	column Banco
		dataType: string
		lineageTag: 8ae8f7ab-1a2c-4b72-bed8-337affa9b3db
		summarizeBy: none
		sourceColumn: Banco

		annotation SummarizationSetBy = Automatic

	column Valor
		dataType: decimal
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 331d403d-90a0-40ca-b3c8-854c6e4dfada
		summarizeBy: sum
		sourceColumn: Valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 867677d4-b90e-4108-a404-c4cb7e3a234e
		summarizeBy: none
		sourceColumn: Data

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Categoria Despesa'
		dataType: string
		lineageTag: e7376f5d-b221-4c68-ab0b-fcbcacb6f1ea
		summarizeBy: none
		sourceColumn: Categoria Despesa

		annotation SummarizationSetBy = Automatic

	column Modalidade
		dataType: string
		lineageTag: 3cc6e27e-961d-4ff3-acb3-77c82e0ca3f0
		summarizeBy: none
		sourceColumn: Modalidade

		annotation SummarizationSetBy = Automatic

	column 'Fonte dinheiro'
		dataType: string
		lineageTag: 71a56618-04c7-41b4-b82b-dee26eab3c55
		summarizeBy: none
		sourceColumn: Fonte dinheiro

		annotation SummarizationSetBy = Automatic

	column 'Qtidade de parcelas'
		dataType: string
		lineageTag: 423a38af-73d0-4892-b8f9-20263616827d
		summarizeBy: none
		sourceColumn: Qtidade de parcelas

		annotation SummarizationSetBy = Automatic

	column Parcela
		dataType: string
		lineageTag: 7ca7f652-e4e0-43ba-9b5d-787784fff662
		summarizeBy: none
		sourceColumn: Parcela

		annotation SummarizationSetBy = Automatic

	column 'Conta origem'
		dataType: string
		lineageTag: a307255e-35a1-47ae-a29c-5919feb5f8c4
		summarizeBy: none
		sourceColumn: Conta origem

		annotation SummarizationSetBy = Automatic

	column 'Tirar linha do dashboard'
		dataType: string
		lineageTag: 0438f7d8-5796-434e-9b65-c686e0ceb43b
		summarizeBy: none
		sourceColumn: Tirar linha do dashboard

		annotation SummarizationSetBy = Automatic

	partition f_despesas = m
		mode: import
		queryGroup: GOLD
		source =
				let
				    Fonte = #"Base de dados",
				    #"Colunas Removidas" = Table.RemoveColumns(Fonte,{"Carimbo de data/hora"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each ([Tipo] = "Despesa")),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Linhas Filtradas",{"Categoria Receitas", "Tipo"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"Valor", Currency.Type}}),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Tipo Alterado", each ([Conta] <> "Casal") and ([Qtidade de parcelas] = "")),
				    #"Consulta Acrescentada" = Table.Combine({#"Linhas Filtradas1", f_despesas_casal_final}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Consulta Acrescentada",{{"Valor", Currency.Type}}),
				    #"Personalização Adicionada" = Table.AddColumn(#"Tipo Alterado1", "Parcela", each ""),
				    #"Colunas Reordenadas" = Table.ReorderColumns(#"Personalização Adicionada",{"Conta", "Título da transação", "Banco", "Valor", "Data", "Categoria Despesa", "Modalidade", "Fonte dinheiro", "Parcela", "Qtidade de parcelas"}),
				    #"Consulta Acrescentada1" = Table.Combine({#"Colunas Reordenadas", f_despesas_parceladas, f_despesas_casal_parceladas_final})
				in
				    #"Consulta Acrescentada1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

